language: go
sudo: required

go:
  - 1.4
  - 1.5
  - 1.6
  - 1.7

go_import_path: github.com/mattes/migrate

services:
  - docker

before_install:
    - sed -i -e 's/golang/golang:'"$TRAVIS_GO_VERSION"'/' docker-compose.yml

script: make test
